strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - build
  - .git
  - __pycache__
  - .eggs
  - dist
  - .tox
  - .cachedocs

pep8:
  options:
    max-line-length: 120
  disable:
    - N815 # mixedCase variable in class scope

mccabe:
  max-complexity: 10

# TODO: Figure out how to replace the functionality provided by:
#       flake8-comprehensions and flake8-print

pylint:
  run: false

pyroma:
  run: false

frosted:
  run: false

vulture:
  run: false

pep257:
  run: false
